"""add image_embedding field

Revision ID: 215c3e77105b
Revises: 93d985be011a
Create Date: 2025-12-07 14:02:26.483788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '215c3e77105b'
down_revision: Union[str, Sequence[str], None] = '93d985be011a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('image_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'image_embedding')
    # ### end Alembic commands ###
