"""initial_schema

Revision ID: 93d985be011a
Revises:
Create Date: 2025-12-06 21:36:28.468475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93d985be011a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Criar tabela clients
    op.create_table('clients',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), nullable=False),
        sa.Column('nickname', sa.VARCHAR(), nullable=True),
        sa.Column('email', sa.VARCHAR(), nullable=False),
        sa.Column('phone', sa.VARCHAR(), nullable=True),
        sa.Column('cpf', sa.VARCHAR(), nullable=True),
        sa.Column('rg', sa.VARCHAR(), nullable=True),
        sa.Column('birth_date', postgresql.TIMESTAMP(), nullable=True),
        sa.Column('is_active', sa.BOOLEAN(), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column('processed', sa.BOOLEAN(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('cpf')
    )

    # Criar tabela client_addresses
    op.create_table('client_addresses',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('client_id', sa.INTEGER(), nullable=False),
        sa.Column('type', sa.VARCHAR(), nullable=False),
        sa.Column('street', sa.VARCHAR(), nullable=False),
        sa.Column('number', sa.VARCHAR(), nullable=False),
        sa.Column('complement', sa.VARCHAR(), nullable=True),
        sa.Column('neighborhood', sa.VARCHAR(), nullable=False),
        sa.Column('city', sa.VARCHAR(), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column('state', sa.VARCHAR(), nullable=False),
        sa.Column('zip_code', sa.VARCHAR(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Criar tabela photos
    op.create_table('photos',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('filename', sa.VARCHAR(), nullable=False),
        sa.Column('original_filename', sa.VARCHAR(), nullable=False),
        sa.Column('file_path', sa.VARCHAR(), nullable=False),
        sa.Column('file_size', sa.INTEGER(), nullable=False),
        sa.Column('content_type', sa.VARCHAR(), nullable=False),
        sa.Column('uploaded_at', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('processed', sa.BOOLEAN(), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('user_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('gemini_file_id', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Remover tabelas criadas no upgrade
    op.drop_table('photos')
    op.drop_table('client_addresses')
    op.drop_table('clients')
    # ### end Alembic commands ###
