"""add processed field to photo table

Revision ID: ba1d45b20131
Revises: 50dd2ede6840
Create Date: 2025-11-30 17:51:19.455121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1d45b20131'
down_revision: Union[str, Sequence[str], None] = '50dd2ede6840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('processed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'processed')
    # ### end Alembic commands ###
