"""Add AI fields to Photo model

Revision ID: bb584c27fa44
Revises: ba1d45b20131
Create Date: 2025-11-30 19:12:24.317556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bb584c27fa44'
down_revision: Union[str, Sequence[str], None] = 'ba1d45b20131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True))
    op.add_column('photo', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'description')
    op.drop_column('photo', 'embedding')
    # ### end Alembic commands ###
