"""add_gemini_file_id_to_photo

Revision ID: e69eeb286029
Revises: 2c1fcf220738
Create Date: 2025-12-05 01:17:05.856585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e69eeb286029'
down_revision: Union[str, Sequence[str], None] = '2c1fcf220738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('gemini_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'gemini_file_id')
    # ### end Alembic commands ###
